### ISSUE TITLE
Fix assets on Heroku

### ISSUE THREAD

**Issue by zuzannast** [netguru-code-college/krk-18-yoda#33]
The assets in main page aż not properly being shown on Heroku.
https://krk-18-yoda.herokuapp.com/

Link to documentation: http://guides.rubyonrails.org/asset_pipeline.html#coding-links-to-assets

**Comment by nikos83** [comment]
I have fixed slider and bottom footer. 
https://tranquil-basin-47005.herokuapp.com/
https://github.com/nikos83/krk-18-yoda

**Comment by zuzannast** [comment]
Good job @nikos83 👏
